### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by sibijosephv** [react-native-market/firebase-authentication-kit#14] opened 2019-11-04 00:30 UTC
Hello, I have an issue with my purchase (7nmYo3bq4GF47v3LIcsj), here are the details of my issue:

I have phone auth enabled. I deleted the user account from firebase, and refreshed the app on the simulator. The user session was still active even after the user itself was deleted from Firebase. Why is it so?

**Comment by Salakar** [comment] 2019-11-17 04:48
Closing as duplicate of #17

**Closed by Salakar** 2019-11-17 04:48 UTC
